### ISSUE TITLE
uninitialized constant ActiveStorage::BaseController (NameError) in RoR 7

### ISSUE THREAD

**Issue by equivalent** [igorkasyanchuk/active_storage_silent_logs#1]
```
=> Rails 7.0.2.4 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
/Users/t/.rvm/gems/ruby-3.0.3@myproect/gems/active_storage_silent_logs-0.1.1/lib/active_storage_silent_logs/railtie.rb:6:in `block in <class:Railtie>': uninitialized constant ActiveStorage::BaseController (NameError)
```

**Comment by igorkasyanchuk** [comment]
@equivalent can you create a PR with a fix? Should be easy I hope. If you have never done it - few tips
- clone this repo
- connect cloned version in Gemfile, by specifying "path"
- do changes (you will need to take a look on active storage, how they changed controllers
- apply change, create PR send to me :)

**Comment by cholguin86** [comment]
I'm having the same problem reported by @equivalent. It looks is an issue related to Zeitwerk, this code loader is not able to load the ActiveStorage::BaseController class. Is there any plan to fix this @igorkasyanchuk?

**Comment by igorkasyanchuk** [comment]
Can you please clone repo and prepare for a PR? Should be easy fix I guess. And I will merge

**Comment by igorkasyanchuk** [comment]
@HirotoYasuda06 I guess you fixed this issue in your PR?

**Comment by HirotoYasuda06** [comment]
Yes. I think so.
